services:
  postgres:
    image: postgres:15-alpine
    container_name: petclinic-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=petclinic
      - POSTGRES_USER=petclinic
      - POSTGRES_PASSWORD=petclinic
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - petclinic-net
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "petclinic", "-d", "petclinic"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    image: alanpham2k2/petclinic
    container_name: petclinic-app
    ports:
      - "9966:9966" 
    environment:
      # Activate the 'postgres' & 'spring-data-jpa' profiles (overwrite application.properties)
      - SPRING_PROFILES_ACTIVE=postgres,spring-data-jpa
      
      # Inject environment variables required by application-postgres.properties
      - POSTGRES_URL=jdbc:postgresql://postgres:5432/petclinic
      - POSTGRES_USER=petclinic
      - POSTGRES_PASS=petclinic
    depends_on:
      postgres:
        condition: service_healthy # Wait for DB to be actually ready, not just started
    networks:
      - petclinic-net

volumes:
  postgres_data:

networks:
  petclinic-net:
    driver: bridge
